function [ts_aux,ws_aux,xs0,ws0] = auxlog_nnode001_naux002()
%CHNK.QUADGALERKIN.AUXLOG_NNODE001_NAUX002
%
% Auxiliary Galerkin quadrature tables generated by
% legeexps_log_lr / hqsuppauxquad from the chunkmatc
% Fortran distribution (logquad_aux.f).
%
%   norder = 1, naux = 2*norder = 2
%
% Nodes are on [-1,1]. xs0{j}/ws0{j} integrate the
% log-singular kernel log|y - ts_aux(j)| times a
% polynomial of degree up to 2*norder-1 over [-1,1].

ts_aux = [
    -6.3212055882855767e-01;
    6.3212055882855767e-01;
];

ws_aux = [
    1.0000000000000000e+00;
    1.0000000000000000e+00;
];

xs0 = cell(2,1);
ws0 = cell(2,1);

xs0{1} = [
    -7.2193377615216137e-01;
    3.3194844339292162e-01;
];
ws0{1} = [
    6.2995358918989997e-01;
    1.3700464108101000e+00;
];

xs0{2} = [
    7.2193377615216137e-01;
    -3.3194844339292162e-01;
];
ws0{2} = [
    6.2995358918989997e-01;
    1.3700464108101000e+00;
];

end
