function [xs1,ws1,xs0,ws0] = getlogquad_aux(k,npolyfac)
%CHNK.QUADGALERKIN.GETLOGQUAD_AUX
%
% Per-target log-singular sub-rules for the Galerkin (aux-projection)
% self block, and an intermediate rule for neighbor panels. Same return
% shape as chnk.quadggq.getlogquad: cell arrays xs0{j}, ws0{j} hold the
% support nodes/weights for the singularity centered at the j-th target
% on the panel, and (xs1, ws1) hold the neighbor-panel intermediate rule.
%
% NOTE (Phase 1 placeholder). The chunkmatc_aux Galerkin scheme uses
% target-dedicated rules generated by the Fortran subroutine
% hqsuppauxquad (file logquad_aux.f in the chunkmatc distribution),
% built for an oversampled auxiliary target distribution. Those tables
% are not yet ported to MATLAB. As a structurally compatible stand-in,
% this function returns the GGQ self-rule tables, which are tuned for
% the k Legendre disc-node target distribution. With these tables the
% Galerkin backend reproduces the GGQ matrix exactly (target-side
% L2 projection is the identity when aux nodes coincide with disc
% nodes). Phase 2 swaps these tables for the true Galerkin auxiliary
% rules; only this function and chnk.quadgalerkin.setup need to change.
%
% input
%   k        - order of disc nodes
%   npolyfac - polynomial-order factor for the rule (default 2)
%
% output: see chnk.quadggq.getlogquad

if nargin < 2
    npolyfac = 2;
end

[xs1,ws1,xs0,ws0] = chnk.quadggq.getlogquad(k,npolyfac);

end
