#!/usr/bin/env python3
"""Format gentab output into chunkie chnk.quadgalerkin table .m files."""
import sys
import os


def parse(stream):
    orders = []
    cur = None
    it = iter(stream)
    for line in it:
        tok = line.split()
        if not tok:
            continue
        if tok[0] == 'ORDER':
            cur = {'n': int(tok[1]), 'naux': int(tok[2]), 'aux': [], 'src': []}
            orders.append(cur)
        elif tok[0] == 'AUX':
            for _ in range(cur['naux']):
                a, b = next(it).split()
                cur['aux'].append((float(a.replace('E', 'e')),
                                   float(b.replace('E', 'e'))))
        elif tok[0] == 'SRC':
            npts = int(tok[2])
            blk = []
            for _ in range(npts):
                a, b = next(it).split()
                blk.append((float(a.replace('E', 'e')),
                            float(b.replace('E', 'e'))))
            cur['src'].append(blk)
    return orders


def fmtcol(name, vals):
    out = ['%s = [' % name]
    out += ['    %.16e;' % v for v in vals]
    out.append('];')
    return out


def emit(o, outdir):
    n, naux = o['n'], o['naux']
    fname = 'auxlog_nnode%03d_naux%03d' % (n, naux)
    L = []
    L.append('function [ts_aux,ws_aux,xs0,ws0] = %s()' % fname)
    L.append('%%CHNK.QUADGALERKIN.%s' % fname.upper())
    L.append('%')
    L.append('% Auxiliary Galerkin quadrature tables generated by')
    L.append('% legeexps_log_lr / hqsuppauxquad from the chunkmatc')
    L.append('% Fortran distribution (logquad_aux.f).')
    L.append('%')
    L.append('%%   norder = %d, naux = 2*norder = %d' % (n, naux))
    L.append('%')
    L.append('% Nodes are on [-1,1]. xs0{j}/ws0{j} integrate the')
    L.append('% log-singular kernel log|y - ts_aux(j)| times a')
    L.append('% polynomial of degree up to 2*norder-1 over [-1,1].')
    L.append('')
    L += fmtcol('ts_aux', [a for a, _ in o['aux']])
    L.append('')
    L += fmtcol('ws_aux', [b for _, b in o['aux']])
    L.append('')
    L.append('xs0 = cell(%d,1);' % naux)
    L.append('ws0 = cell(%d,1);' % naux)
    for j, blk in enumerate(o['src'], start=1):
        L.append('')
        L += fmtcol('xs0{%d}' % j, [a for a, _ in blk])
        L += fmtcol('ws0{%d}' % j, [b for _, b in blk])
    L.append('')
    L.append('end')
    L.append('')
    path = os.path.join(outdir, fname + '.m')
    with open(path, 'w') as f:
        f.write('\n'.join(L))
    print('wrote %s (naux=%d, npts=%s)' %
          (path, naux, sorted({len(b) for b in o['src']})))


if __name__ == '__main__':
    outdir = sys.argv[1]
    for o in parse(sys.stdin):
        emit(o, outdir)
